/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CareerFocusScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CertificationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CountryScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CurrentFieldScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CurrentSituationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/FinalStepScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/ForgotPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/GetStart`; params?: Router.UnknownInputParams; } | { pathname: `/pages/GoalSelectionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/GoalTimelineScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/page2`; params?: Router.UnknownInputParams; } | { pathname: `/pages/page3`; params?: Router.UnknownInputParams; } | { pathname: `/pages/ResetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/pages/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/TargetRoleScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/WelcomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/CareerFocusScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/CertificationScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/CountryScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/CurrentFieldScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/CurrentSituationScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/FinalStepScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/ForgotPasswordScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/GetStart`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/GoalSelectionScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/GoalTimelineScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/LoginScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/page2`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/page3`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/ResetPassword`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/SignUpScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/TargetRoleScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/pages/WelcomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/pages/CareerFocusScreen${`?${string}` | `#${string}` | ''}` | `/pages/CertificationScreen${`?${string}` | `#${string}` | ''}` | `/pages/CountryScreen${`?${string}` | `#${string}` | ''}` | `/pages/CurrentFieldScreen${`?${string}` | `#${string}` | ''}` | `/pages/CurrentSituationScreen${`?${string}` | `#${string}` | ''}` | `/pages/FinalStepScreen${`?${string}` | `#${string}` | ''}` | `/pages/ForgotPasswordScreen${`?${string}` | `#${string}` | ''}` | `/pages/GetStart${`?${string}` | `#${string}` | ''}` | `/pages/GoalSelectionScreen${`?${string}` | `#${string}` | ''}` | `/pages/GoalTimelineScreen${`?${string}` | `#${string}` | ''}` | `/pages/LoginScreen${`?${string}` | `#${string}` | ''}` | `/pages/page2${`?${string}` | `#${string}` | ''}` | `/pages/page3${`?${string}` | `#${string}` | ''}` | `/pages/ResetPassword${`?${string}` | `#${string}` | ''}` | `/pages/SignUpScreen${`?${string}` | `#${string}` | ''}` | `/pages/TargetRoleScreen${`?${string}` | `#${string}` | ''}` | `/pages/WelcomeScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CareerFocusScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CertificationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CountryScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CurrentFieldScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/CurrentSituationScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/FinalStepScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/ForgotPasswordScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/GetStart`; params?: Router.UnknownInputParams; } | { pathname: `/pages/GoalSelectionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/GoalTimelineScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/LoginScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/page2`; params?: Router.UnknownInputParams; } | { pathname: `/pages/page3`; params?: Router.UnknownInputParams; } | { pathname: `/pages/ResetPassword`; params?: Router.UnknownInputParams; } | { pathname: `/pages/SignUpScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/TargetRoleScreen`; params?: Router.UnknownInputParams; } | { pathname: `/pages/WelcomeScreen`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
